### ISSUE TITLE
[Suggestion] Can u make Readme file explain more clearly

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_AsyncLoggers#1]
i know this is a good mod, and i know ur also lobbycontrol creator
but can u fix some typo issues......

**Comment by mattymatty97** [comment]
good idea for the typos, i did write that readme in a hurry

but not really sure what should be added more to the redame. as explaining the inner workings or why it helps performace would be way too technical for normal users to understand 🤔
