### ISSUE TITLE
[Suggestion/QOL] globally set the log level to all the mod logs, and add preserve config option, and loglevel for Unity Log only, `All In Base Config`

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_AsyncLoggers#12]
@mattymatty97 same as topic, can u made a quick update? previously i used `lesslog` to block the logs, but will cause lagging when log console spaming with error logs.

**Comment by CoolLKKPS** [comment]
changed title

**Comment by mattymatty97** [comment]
i'm not too sure about what you're requesting, but you should probably check the LogLevels config file in the AsyncLoggers folder

**Comment by CoolLKKPS** [comment]
so
1. globally set the log level for every source, and remove those logs even in `%AppData%\..\LocalLow\ZeekerssRBLX\Lethal Company\Player.log`, i want completely remove not just not appear
2. if i set the log level for some source, then sometime i want to keep the loglevel setting, this mod should have option to keep the setting, i call `preserve config`
3. Unity Log is special, so Unity Log should not appear in `LogLevel.cfg`
