### ISSUE TITLE
[Question] does this work for other bepinex modded unity games?

### ISSUE THREAD

**Issue by CatsArmy** [mattymatty97/LTC_AsyncLoggers#2]
just wondering as this could help performence in other games too

**Comment by mattymatty97** [comment]
in theory this targets BepInEx and Unity only, so it should be compatible with any other game

i haven't had a chance to test it yet tho

**Comment by CatsArmy** [comment]
> in theory this targets BepInEx and Unity only, so it should be compatible with any other game
> 
> i haven't had a chance to test it yet tho

ty

**Comment by CatsArmy** [comment]
alright so yea it does 100% work with other games from what I've seen(could you also upload it to rounds?)

**Comment by mattymatty97** [comment]
i need to ask TS staff if there is a way to mark my mod for multiple/all games 🤔

**Comment by CatsArmy** [comment]
You don't need to I'm pretty sure it's just like when selecting mod tags I believe like client side and stuff

**Comment by mattymatty97** [comment]
![image](https://github.com/mattymatty97/LTC_AsyncLoggers/assets/33039934/836a5a02-7d73-42b4-98e1-ac0f89f08a5c)
for now here it is, but i want to try and ask TS staff if it can be marked for ALL games as R2Modman and BepInEx are

**Comment by CatsArmy** [comment]
Can you not mark it for more than 2 games? Or are you referring to the version of bepinex and unity those games use

**Comment by mattymatty97** [comment]
right. i need to change the target BepInEx version too

**Comment by CatsArmy** [comment]
@mattymatty97  sorry for the ping but could you also publish the mod to ror2 (risk of rain)?
