### ISSUE TITLE
Softlock during BepinEx loading phase

### ISSUE THREAD

**Issue by ZigzagAwaka** [mattymatty97/LTC_AsyncLoggers#6]
I can't really document this issue since its coming from a friend of mine.
This mod is doing parallel loads and BepinEx loading phase seems to softlock when using this mod and having a bad CPU (or old pc, idk)

My friend has a 2 core cpu and he can't start the game unless this mod is disabled (tested in v49)

Like i said, since this issue doesn't came from me, i will not be able to help towards a potential solution, and this posted issue is just for observation/documentation purpose

![Capture](https://github.com/mattymatty97/LTC_AsyncLoggers/assets/122373808/e16e61f2-a04c-4c50-9f3c-5fa18bff7d26)

**Comment by mattymatty97** [comment]
i've been able to run it ( albeit really slow ) in both a 2 core 4 thread scenario and a 1 core 1 thread one.
the mod itself is coded to avoid any blocking operations to allow for full parallelism so i'm not really sure what is causing issues

might be a specific mod combination

**Comment by ZigzagAwaka** [comment]
This is the profile we used 018ec328-d510-38fa-3d94-bbf22d8e3caa
I also asked my friend to disable "Bepinex Faster Load AssetBundle Patcher" to see if it was a conflict with AsyncLoggers but no it didn't solve anything

**Comment by mattymatty97** [comment]
nope profile is booting perfectly fine even with a single cpu single thread

**Comment by mattymatty97** [comment]
i can see the profile is using v1.6.1
in that version there was a bug that was crashing LobbyControl/MattyFixes ( or any other mod relying on Async tbh) when there were two or more LogOutput.sqlite files in the log folder

**Comment by mattymatty97** [comment]
you can see the folder with
![image](https://github.com/mattymatty97/LTC_AsyncLoggers/assets/33039934/dbe373d3-c898-4c01-947c-c0854313c389)
and then navigate inside the BepInEx subfolder

**Comment by ZigzagAwaka** [comment]
Don't worry i know how to navigate in the profile folder :)
But I didn't saw any log folder inside BepinEx, and we didn't used any async mods iirc

Are you sure the issue does not come from the cpu ? If this is true, i have no idea how to help you solve it....
